repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
-   repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v1.0.0
    hooks:
    -   id: runic
fail_fast: true
