name = "DifferentiationInterface"
uuid = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
authors = ["Guillaume Dalle", "Adrian Hill"]
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Diffractor = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
DifferentiationInterfaceChainRulesCoreExt = "ChainRulesCore"
DifferentiationInterfaceChairmarksExt = ["Chairmarks"]
DifferentiationInterfaceDiffractorExt = [
    "AbstractDifferentiation",
    "Diffractor",
]
DifferentiationInterfaceEnzymeExt = "Enzyme"
DifferentiationInterfaceFastDifferentiationExt = [
    "FastDifferentiation",
    "RuntimeGeneratedFunctions",
]
DifferentiationInterfaceFiniteDiffExt = "FiniteDiff"
DifferentiationInterfaceFiniteDifferencesExt = "FiniteDifferences"
DifferentiationInterfaceForwardDiffExt = ["DiffResults", "ForwardDiff"]
DifferentiationInterfaceJETExt = ["JET"]
DifferentiationInterfacePolyesterForwardDiffExt = [
    "PolyesterForwardDiff",
    "ForwardDiff",
    "DiffResults",
]
DifferentiationInterfaceReverseDiffExt = ["DiffResults", "ReverseDiff"]
DifferentiationInterfaceTrackerExt = ["Tracker"]
DifferentiationInterfaceZygoteExt = ["Zygote"]

[compat]
ADTypes = "0.2.7"
AbstractDifferentiation = "0.6"
Chairmarks = "1.2"
ChainRulesCore = "1.19"
DiffResults = "1.1"
Diffractor = "0.2"
DocStringExtensions = "0.9"
Enzyme = "0.11"
FastDifferentiation = "0.3"
FillArrays = "1"
FiniteDiff = "2.22"
FiniteDifferences = "0.12"
ForwardDiff = "0.10"
JET = "0.8"
LinearAlgebra = "1"
PolyesterForwardDiff = "0.1"
ReverseDiff = "1.15"
RuntimeGeneratedFunctions = "0.5"
Test = "1"
Tracker = "0.2"
Zygote = "0.6"
julia = "1.10"
