steps:
  - label: "DI GPU tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia ./DifferentiationInterface/test/GPU/CUDA/main.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60