name: Pre-Commit

on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Julia
        uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install pre-commit
        run: uv tool install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color always
